import image1 from "./images/pass.jpg";
import image1b from "./images/snazzo.jpg";
import image2 from "./images/fred.jpg";
import image2b from "./images/eneche.jpg";
import image3 from "./images/kab2.jpg";
import image3b from "./images/kabir.jpg";
import patA from "./images/paternusA.jpg";
import patB from "./images/paternusB.jpg";
import samA from "./images/samA.jpg";
import samB from "./images/samB.jpg";
import kafayatA from "./images/kafayatA.jpg";
import kafayatB from "./images/kafayatB.jpg";
import snazzypdf from "./graduates_projects/SNAZZY-PROJECT.pdf";
import alabipdf from "./graduates_projects/Alabi.pdf";
console.log(image1);
export const data = [
  {
    id: 1,
    name: "nuhu haruna",
    image: image1,
    imageb: image1b,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "Dietician",
    department: "RSG",
    quote: "Laissez faire",
    project: alabipdf,
    about:
      " I'm sapiosexual, nihilist and a lover of philosohpy....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 2,
    name: "james callagher",
    image: image2,
    imageb: image2b,
    facebook: "https://www.james.com",
    twitter: "https://www.snazzy.com",
    linkedin: "https://www.snazzy.com",
    profession: "Remote sensing expert",
    department: "RSG and GIS",
    quote: "Laissez faire",
    about:
      " The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 3,
    name: "Kabir Dexcode",
    image: image3,
    imageb: image3b,
    facebook: "https://www.kabir.com",
    twitter: "https://www.snazzy.com",
    linkedin: "https://www.snazzy.com",
    profession: "Web Developer",
    department: "SATCOM",
    quote: "Laissez faire",
    about:
      " The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 4,
    name: "sarajudeen kafayat",
    image: kafayatA,
    imageb: kafayatB,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "Geologist",
    department: "RSG",
    quote: "Ayewada, ko si aye",
    project: alabipdf,
    about:
      " I'm sarajudeen kafayat and a lover of rocks....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 5,
    name: "Aruwa Samson",
    image: samA,
    imageb: samB,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "chief security officer",
    department: "RSG",
    quote: "A stitch in time saves nine",
    project: alabipdf,
    about:
      " I'm Aruwa Samson and a firm believer of a better Nigeria....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 6,
    name: "paternus cleophace",
    image: patA,
    imageb: patB,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "surveyor",
    department: "SATCOM",
    quote: "I go crush you",
    project: alabipdf,
    about:
      " Please call me King Solomon and a firm believer of a better Nigeria....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 1,
    name: "nuhu haruna",
    image: image1,
    imageb: image1b,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "Dietician",
    department: "RSG",
    quote: "Laissez faire",
    project: alabipdf,
    about:
      " I'm sapiosexual, nihilist and a lover of philosohpy....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 2,
    name: "james callagher",
    image: image2,
    imageb: image2b,
    facebook: "https://www.james.com",
    twitter: "https://www.snazzy.com",
    linkedin: "https://www.snazzy.com",
    profession: "Remote sensing expert",
    department: "RSG and GIS",
    quote: "Laissez faire",
    about:
      " The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 3,
    name: "Kabir Dexcode",
    image: image3,
    imageb: image3b,
    facebook: "https://www.kabir.com",
    twitter: "https://www.snazzy.com",
    linkedin: "https://www.snazzy.com",
    profession: "Web Developer",
    department: "SATCOM",
    quote: "Laissez faire",
    about:
      " The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 4,
    name: "sarajudeen kafayat",
    image: kafayatA,
    imageb: kafayatB,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "Geologist",
    department: "RSG",
    quote: "Ayewada, ko si aye",
    project: alabipdf,
    about:
      " I'm sarajudeen kafayat and a lover of rocks....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 5,
    name: "Aruwa Samson",
    image: samA,
    imageb: samB,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "chief security officer",
    department: "RSG",
    quote: "A stitch in time saves nine",
    project: alabipdf,
    about:
      " I'm Aruwa Samson and a firm believer of a better Nigeria....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 6,
    name: "paternus cleophace",
    image: patA,
    imageb: patB,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "surveyor",
    department: "SATCOM",
    quote: "I go crush you",
    project: alabipdf,
    about:
      " Please call me King Solomon and a firm believer of a better Nigeria....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 1,
    name: "nuhu haruna",
    image: image1,
    imageb: image1b,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "Dietician",
    department: "RSG",
    quote: "Laissez faire",
    project: alabipdf,
    about:
      " I'm sapiosexual, nihilist and a lover of philosohpy....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 2,
    name: "james callagher",
    image: image2,
    imageb: image2b,
    facebook: "https://www.james.com",
    twitter: "https://www.snazzy.com",
    linkedin: "https://www.snazzy.com",
    profession: "Remote sensing expert",
    department: "RSG and GIS",
    quote: "Laissez faire",
    about:
      " The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 3,
    name: "Kabir Dexcode",
    image: image3,
    imageb: image3b,
    facebook: "https://www.kabir.com",
    twitter: "https://www.snazzy.com",
    linkedin: "https://www.snazzy.com",
    profession: "Web Developer",
    department: "SATCOM",
    quote: "Laissez faire",
    about:
      " The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 4,
    name: "sarajudeen kafayat",
    image: kafayatA,
    imageb: kafayatB,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "Geologist",
    department: "RSG",
    quote: "Ayewada, ko si aye",
    project: alabipdf,
    about:
      " I'm sarajudeen kafayat and a lover of rocks....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 5,
    name: "Aruwa Samson",
    image: samA,
    imageb: samB,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "chief security officer",
    department: "RSG",
    quote: "A stitch in time saves nine",
    project: alabipdf,
    about:
      " I'm Aruwa Samson and a firm believer of a better Nigeria....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
  {
    id: 6,
    name: "paternus cleophace",
    image: patA,
    imageb: patB,
    facebook: "#",
    twitter: "https://twitter.com/NuhSnazzy",
    linkedin: "https://www.linkedin.com/in/nuhu-haruna-602164154/",
    profession: "surveyor",
    department: "SATCOM",
    quote: "I go crush you",
    project: alabipdf,
    about:
      " Please call me King Solomon and a firm believer of a better Nigeria....The best Lorem Ipsum Generator in all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg! n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!n all the sea! Heave this scurvy copyfiller fer yar next adventure and cajol yar clients into walking the plank with every layout! Configure above, then get yer pirate ipsum...own the high seas, arg!",
  },
];
